services:
  backend:
    image: opennds-auth
    build: .
    restart: always
    volumes:
      - "./data:/home/pi"
    ports:
      - '8080:80'
    tty: true
    environment:
      - LDAP_SERVER=127.0.0.1:389
